### PR TITLE
feat: emit to directory other than source root

### PR DESCRIPTION
**Pull request by lbennett-stacki**
I wanted to emit straight to my `dist` dir, otherwise, I get a bunch of source declarations that I don't need to track in my project, as I only want to publish the types for consumers.

Without this, I would need a second step in my build to move all source declarations, and even that is a little janky.

With this change, we can set the source and output directories as simple absolute paths and be done with it 👍

### CODE REVIEW

**Comment by lbennett-stacki** [comment]
Ready for review @activeguild :)

**Comment by activeguild** [comment]
@lbennett-stacki 
Thank you. I'll review it tonight.

**Comment by activeguild** [comment]
@lbennett-stacki 
Can you add new options to the `README`?

**Comment by lbennett-stacki** [comment]
@activeguild ahh yep, will do, thanks!

**Comment by lbennett-stacki** [comment]
@activeguild ready to go!

**Comment by activeguild** [comment]
Thank you!!

**Review by activeguild — APPROVED** [review]

**Pull request merged**
